database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.cj.jdbc.Driver
    # the username
    user: root
    #user: root
    # the password
    password: welcome
    #password:
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/testdb
    properties:
      charSet: UTF-8